import type { Metadata } from "next";
import "./globals.css";
import { Inter as FontSans } from "next/font/google";
import { cn } from "@/lib/utils";
import { NavBar } from "./navBar";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head />
      <body
        className={cn(
          "bg-background font-sans antialiased overflow-y-hidden ",
          fontSans.variable
        )}
      >
        <header className="z-50 relative">
          <NavBar />
        </header>
        <main className="bg-customBgAccent">{children}</main>
      </body>
    </html>
  );
}
